# Documentation: https://github.com/actions/labeler

"area/infra":
  - changed-files:
      - any-glob-to-any-file: 
          - '.github/**/*'
          - 'workflows/**/*'

"area/docs":
  - changed-files:
      - any-glob-to-any-file:
          - 'docs/**/*'
          - '**/*.md'
          - 'README.md'

"area/automation":
  - changed-files:
      - any-glob-to-any-file:
          - 'scripts/**/*'
          - 'tools/**/*'
