# Still Systems Organization Labeler
# This configuration is inherited by all repositories in the organization.

"area: documentation":
  - any: ['**/*.md', 'docs/**']

"area: github-actions":
  - any: ['.github/workflows/**']

"area: configuration":
  - any: ['.github/*.yml', '.github/*.md', '.gitignore', 'package.json', 'go.mod', 'pyproject.toml']

"area: branding":
  - any: ['.github/brand/**', 'assets/logo/**']
