name: Reusable Go CI

on:
  workflow_call:
    inputs:
      go-version:
        required: false
        type: string
        default: '1.24.2'
      working-directory:
        required: false
        type: string
        default: '.'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: ${{ inputs.go-version }}
          check-latest: true
      - name: Verify dependencies
        run: go mod verify
        working-directory: ${{ inputs.working-directory }}
      - name: Build
        run: go build -v ./...
        working-directory: ${{ inputs.working-directory }}
      - name: Test
        run: go test -v -race -coverprofile=coverage.txt -covermode=atomic ./...
        working-directory: ${{ inputs.working-directory }}
