name: Reusable Node CI

on:
  workflow_call:
    inputs:
      node-version:
        required: false
        type: string
        default: '20.x'
      working-directory:
        required: false
        type: string
        default: '.'
      run-xvfb:
        required: false
        type: boolean
        default: false

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: ${{ inputs.node-version }}
          cache: 'npm'
          cache-dependency-path: ${{ inputs.working-directory }}/package-lock.json
      - name: Install Dependencies
        working-directory: ${{ inputs.working-directory }}
        run: npm ci
      - name: Lint
        working-directory: ${{ inputs.working-directory }}
        run: npm run lint --if-present
      - name: Test (with Xvfb)
        if: ${{ inputs.run-xvfb }}
        working-directory: ${{ inputs.working-directory }}
        run: xvfb-run -a npm run test --if-present
      - name: Test (without Xvfb)
        if: ${{ !inputs.run-xvfb }}
        working-directory: ${{ inputs.working-directory }}
        run: npm run test --if-present
      - name: Audit
        working-directory: ${{ inputs.working-directory }}
        run: npm audit --audit-level=high
